### ISSUE TITLE
Nav-Bar Issue 

### ISSUE THREAD

**Issue by vaibhavmodi45** [programmer-rahul/personal-portfolio#8]
On exploring the website on a mobile then there is an issue that arises that the nav-Bar toggle button is not showing the drop down list (which we can expect from it).

**Comment by programmer-rahul** [comment]
Hi @vaibhavmodi45,

Thanks for bringing this up. Actually, the dropdown menu is hidden when the website is opened on small devices because the nav-bar is not yet designed for smaller screens. Given that this is a personal portfolio, I don't think we need a navbar for smaller devices. Perhaps we should remove the navbar-toggle button entirely. What do you think?

**Comment by vaibhavmodi45** [comment]
Hello @programmer-rahul 

This is a good idea, we can think about removing it cause on small devices generally users keep scroll so as per that scenario there will be no need for a navbar.

**Comment by programmer-rahul** [comment]
Hi @vaibhavmodi45,

Yes, we can remove the navbar-toggle button as it seems unnecessary for small devices. If you’d like, you can go ahead and make this change.

**Comment by vaibhavmodi45** [comment]
Hii @programmer-rahul , 

I've tried to make some updates that are needed by you as we have discussed i.e. the Navbar Icon. I've removed it please make sure and verify it and if all is good then you can merge it.

**Comment by programmer-rahul** [comment]
Hi @vailbhavmodi45,  
You also need to remove the code where this dropdown menu icon has been imported and used. Otherwise, it will cause errors because this is no longer available.

**Comment by vaibhavmodi45** [comment]
Made the customzation but they are not appropriate as per the Project Owner so the issue commits are not considered.
